import './globals.css'
import type { Metadata } from 'next'
import { Html } from 'next/document'
import { Literata } from 'next/font/google'

const inter = Literata({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Patrícia Beckmann Dentista',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className} bg-slate-200 overflow-hidden`}>{children}</body>
    </html>
  )
}
